 version: '3'
 services:
  db:
    build: 
      # Dockerfileのあるディレクトリのパスを指定
      context: ./docker/mysql
    container_name: echo-mysql
    ports: 
      # 公開ポートを指定
      - "3306:3306"
    volumes: 
      # 起動時にデータの初期化を行う
      - ./docker/mysql/db:/docker-entrypoint-initdb.d
      # mysqlの永続化
      - ./docker/mysql/db/mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_system_echo
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  go:
    build:
      context: ./docker/golang
    container_name: echo-golang
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: fresh

  nodejs:
    build:
      context: ./docker/nodejs
    container_name: echo-nodejs
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    # command: sh -c "cd assets && yarn install && yarn serve"